/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AbilitaEroiIndexRouteImport } from './routes/abilita-eroi/index'
import { Route as AbilitaEroiHeroIdRouteImport } from './routes/abilita-eroi/$heroId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AbilitaEroiIndexRoute = AbilitaEroiIndexRouteImport.update({
  id: '/abilita-eroi/',
  path: '/abilita-eroi/',
  getParentRoute: () => rootRouteImport,
} as any)
const AbilitaEroiHeroIdRoute = AbilitaEroiHeroIdRouteImport.update({
  id: '/abilita-eroi/$heroId',
  path: '/abilita-eroi/$heroId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/abilita-eroi/$heroId': typeof AbilitaEroiHeroIdRoute
  '/abilita-eroi/': typeof AbilitaEroiIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/abilita-eroi/$heroId': typeof AbilitaEroiHeroIdRoute
  '/abilita-eroi': typeof AbilitaEroiIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/abilita-eroi/$heroId': typeof AbilitaEroiHeroIdRoute
  '/abilita-eroi/': typeof AbilitaEroiIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/abilita-eroi/$heroId' | '/abilita-eroi/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/abilita-eroi/$heroId' | '/abilita-eroi'
  id: '__root__' | '/' | '/abilita-eroi/$heroId' | '/abilita-eroi/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AbilitaEroiHeroIdRoute: typeof AbilitaEroiHeroIdRoute
  AbilitaEroiIndexRoute: typeof AbilitaEroiIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/abilita-eroi/': {
      id: '/abilita-eroi/'
      path: '/abilita-eroi'
      fullPath: '/abilita-eroi/'
      preLoaderRoute: typeof AbilitaEroiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/abilita-eroi/$heroId': {
      id: '/abilita-eroi/$heroId'
      path: '/abilita-eroi/$heroId'
      fullPath: '/abilita-eroi/$heroId'
      preLoaderRoute: typeof AbilitaEroiHeroIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AbilitaEroiHeroIdRoute: AbilitaEroiHeroIdRoute,
  AbilitaEroiIndexRoute: AbilitaEroiIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
